AWSTemplateFormatVersion: '2010-09-09'
Metadata:
  License: Apache-2.0
Description: 'AWS CloudFormation Sample Template DynamoDB_Table'
Parameters:
  ReadCapacityUnits:
    Description: Provisioned read throughput
    Type: Number
    Default: '5'
    MinValue: '5'
    MaxValue: '10000'
    ConstraintDescription: must be between 5 and 10000
  WriteCapacityUnits:
    Description: Provisioned write throughput
    Type: Number
    Default: '5'
    MinValue: '5'
    MaxValue: '10000'
    ConstraintDescription: must be between 5 and 10000
Resources:
  IPTRANSACTION:
    Type: AWS::DynamoDB::Table
    Properties:       
      AttributeDefinitions:
      - AttributeName: "TransactionalId"
        AttributeType: "S"
      - AttributeName: "ApplicationId"
        AttributeType: "S"
      - AttributeName: "IpBlockflag"
        AttributeType: "S"
      - AttributeName: "CreatedTimestamp"
        AttributeType: "S"         
      KeySchema:
      - AttributeName: "TransactionalId"
        KeyType: "HASH"
      - AttributeName: "ApplicationId"
        KeyType: "RANGE"                               
      ProvisionedThroughput:
        ReadCapacityUnits: !Ref 'ReadCapacityUnits'
        WriteCapacityUnits: !Ref 'WriteCapacityUnits'
      TableName: "IPTRANSACTIONS"
      TimeToLiveSpecification:
        AttributeName: "ttl"
        Enabled: "true"
      ProvisionedThroughput:
        ReadCapacityUnits: !Ref 'ReadCapacityUnits'
        WriteCapacityUnits: !Ref 'WriteCapacityUnits'   
      ContributorInsightsSpecification:
        Enabled: "true"
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: "true"
      GlobalSecondaryIndexes:
        - IndexName: "UserId-AppId-index"
          KeySchema:
          - AttributeName: "IpBlockflag"
            KeyType: "HASH"
          - AttributeName: "CreatedTimestamp"
            KeyType: "RANGE"    
          Projection:
            ProjectionType: "ALL"
          ContributorInsightsSpecification:
            Enabled: "true"
          ProvisionedThroughput:
            ReadCapacityUnits: !Ref 'ReadCapacityUnits'
            WriteCapacityUnits: !Ref 'WriteCapacityUnits'        
