AWSTemplateFormatVersion: '2010-09-09'
Metadata:
  License: Apache-2.0
Description: 'AWS CloudFormation Sample Template DynamoDB_Table'
Parameters:
  ReadCapacityUnits:
    Description: Provisioned read throughput
    Type: Number
    Default: '5'
    MinValue: '5'
    MaxValue: '10000'
    ConstraintDescription: must be between 5 and 10000
  WriteCapacityUnits:
    Description: Provisioned write throughput
    Type: Number
    Default: '5'
    MinValue: '5'
    MaxValue: '10000'
    ConstraintDescription: must be between 5 and 10000
Resources:
  IDMDevicePreference:
    Type: AWS::DynamoDB::Table
    DeletionPolicy: Retain
    Properties:   
      Tags: 
      - Key: "IDMDevicePreference-IDM"
        Value: "IDM"      
      AttributeDefinitions:
      - AttributeName: "Username"
        AttributeType: "S"
      - AttributeName: "DeviceId"
        AttributeType: "S"
      - AttributeName: "TargetDevice"
        AttributeType: "S"
      KeySchema:
      - AttributeName: "Username"
        KeyType: "HASH"
      - AttributeName: "DeviceId"
        KeyType: "RANGE"
      ProvisionedThroughput:
        ReadCapacityUnits: !Ref 'ReadCapacityUnits'
        WriteCapacityUnits: !Ref 'WriteCapacityUnits'
      TableName: "IDMDevicePreference"
      TimeToLiveSpecification:
        AttributeName: "ttl"
        Enabled: "true"
      ProvisionedThroughput:
        ReadCapacityUnits: !Ref 'ReadCapacityUnits'
        WriteCapacityUnits: !Ref 'WriteCapacityUnits'   
      ContributorInsightsSpecification:
        Enabled: "true"
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: "true"
      GlobalSecondaryIndexes:
        - IndexName: "TargetDevice-index"
          KeySchema:
          - AttributeName: "TargetDevice"
            KeyType: "HASH"          
          Projection:
            ProjectionType: "ALL"
          ContributorInsightsSpecification:
            Enabled: "true"
          ProvisionedThroughput:
            ReadCapacityUnits: !Ref 'ReadCapacityUnits'
            WriteCapacityUnits: !Ref 'WriteCapacityUnits'
