version=0.1
[default.global.parameters]
stack_name = "RestApi"
 
[default.deploy.parameters]
region = "us-west-2"
s3_bucket = "REPLACE_BUCKET_NAME"
s3_prefix = "api"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
tags = "project=\"ca-labs\" stage=\"development\""
